### ISSUE TITLE
Node.js Documentation

### ISSUE THREAD

**Issue by stlgolfer** [MICDSRobotics/Technomaric5190Website#13]
# Overview
We might want to start actually documenting our 'back-end' of our site as more routes are added and our library gets more complicated

# Solution
Maybe use [this node.js documentation npm package](https://github.com/documentationjs/documentation)

**Comment by nickbclifford** [comment]
If we were to do this, we should probably use [JSDoc](https://github.com/jsdoc3/jsdoc) since it's the standard documentation generator for JavaScript.

**Comment by stlgolfer** [comment]
I'm pretty sure `documentation` uses JSDoc. I think it's just a simpler CLI
